"""create tenant and widget type tables

Revision ID: 444f88d737cd
Revises: 
Create Date: 2026-08-30 18:52:55.065616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444f88d737cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_index(op.f('ix_tenant_customer_email'), 'tenant', ['customer_email'], unique=True)
    op.create_table('widget_type',
    sa.Column('widget_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('widget_type_id')
    )
    op.create_index(op.f('ix_widget_type_name'), 'widget_type', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_widget_type_name'), table_name='widget_type')
    op.drop_table('widget_type')
    op.drop_index(op.f('ix_tenant_customer_email'), table_name='tenant')
    op.drop_table('tenant')
    # ### end Alembic commands ###
