"""create field definition and widget field tables

Revision ID: 67f5c259c29b
Revises: 8a4203814732
Create Date: 2026-08-30 19:32:13.531027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f5c259c29b'
down_revision: Union[str, Sequence[str], None] = '8a4203814732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_definition',
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('field_id')
    )
    op.create_table('widget_field',
    sa.Column('widget_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['field_definition.field_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['widget_id'], ['widget.widget_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('widget_id', 'field_id'),
    sa.UniqueConstraint('widget_id', 'field_id', name='uq_widget_field_widget_id_field_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('widget_field')
    op.drop_table('field_definition')
    # ### end Alembic commands ###
