"""create widget table

Revision ID: 8a4203814732
Revises: 444f88d737cd
Create Date: 2026-08-30 19:03:36.066235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a4203814732'
down_revision: Union[str, Sequence[str], None] = '444f88d737cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget',
    sa.Column('widget_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('widget_type_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('allowed_origins', postgresql.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['widget_type_id'], ['widget_type.widget_type_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('widget_id')
    )
    op.create_index(op.f('ix_widget_tenant_id'), 'widget', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_widget_widget_type_id'), 'widget', ['widget_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_widget_widget_type_id'), table_name='widget')
    op.drop_index(op.f('ix_widget_tenant_id'), table_name='widget')
    op.drop_table('widget')
    # ### end Alembic commands ###
